### ISSUE TITLE
How to train objects with large width height ratio

### ISSUE THREAD

**Issue by xiaoshun1007** [open-mmlab/mmrotate#285]
![image](https://user-images.githubusercontent.com/74587741/167325936-6280171f-5445-45a9-acfd-5922bf27d7c9.png)

我想识别导线的方向，模型精度很差，甚至难以拟合，是因为目标的宽高的比值太大吗？应该如何训练此类物体？
I want to identify the direction of the wire. The accuracy of the model is very poor, or even difficult to fit. Is it because the ratio of the width to height of the target is too large?How should such objects be trained?

**Comment by GamblerZSY** [comment]
The object in the figure does have an extreme aspect ratio, which is uncommon in the existing public dataset. If you tried a detector based on the anchor mechanism, the recall may not be ideal, because it is difficult to find suitable positive samples during the label assignment. You can try to lower the positive sample threshold, but I can't guarantee that the accuracy can be effectively improved.

**Comment by xiaoshun1007** [comment]
请问咱们模型库里哪些不是基于anchor机制的模型？
Which models in our model zoo are not based on the anchor mechanism?

**Comment by GamblerZSY** [comment]
>

> 请问咱们模型库里哪些不是基于anchor机制的模型？ Which models in our model zoo are not based on the anchor mechanism?

> 请问咱们模型库里哪些不是基于anchor机制的模型？ Which models in our model zoo are not based on the anchor mechanism?

Configs without 'anchor_generator' field, such as rotated_reppoints, sasm_reppoints...

**Comment by yangxue0827** [comment]
Some anchor free methods is in PR processing:
fcos: https://github.com/open-mmlab/mmrotate/pull/223
oriented reppoints: https://github.com/open-mmlab/mmrotate/pull/286
