### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by wjl0512** [open-mmlab/mmrotate#297]
Why is there no resnet.py in backbones and no fpn.py in necks?

**Comment by GamblerZSY** [comment]
> Why is there no resnet.py in backbones and no fpn.py in necks?

Because they are not in MMRotate, but in MMDetection. If you used 'pip install mmdet' to install MMDetection, they exist in your path '/home/xxx/anaconda3/envs/your env name/lib/python3.7/site-packages/mmdet/models'. If you build MMDetection from source, you can find them in the path that MMDetection is saved.
