### ISSUE TITLE
Not found cuda.

### ISSUE THREAD

**Issue by AndrewWangCH** [open-mmlab/mmrotate#395]
Hi, I run demo but get a error.

This is error:   
File "C:\Users\jlin04\.conda\envs\mmlabV2\lib\site-packages\mmcv\ops\nms.py", line 28, in forward
    inds = ext_module.nms(
RuntimeError: nms_impl: implementation for device cu
da:0 not found.

But I  print(torch.cuda.is_available()) is True.
So I don't know why.

![1](https://user-images.githubusercontent.com/59794732/177255879-80417ca3-5586-4769-a1ba-a1a10626acf9.png)
![2](https://user-images.githubusercontent.com/59794732/177255888-9e19e632-4db2-43f5-8bb4-c949963345c1.png)

**Comment by zytx121** [comment]
It may be caused by the mmcv-full which you installed is the CPU version. Please refer [here](https://github.com/open-mmlab/mmcv#installation) to install the right mmcv-full
<img width="849" alt="image" src="https://user-images.githubusercontent.com/10410257/177455602-59935349-7286-4258-a91c-5b6505b26a3b.png">

**Comment by AndrewWangCH** [comment]
I install mmcv-full in here, and I not install cudatoolkit11.3 that cause error?

**Comment by zytx121** [comment]
Yes, you need to install `cudatoolkit`, whose version is the same as `mmcv-full` you have installed.

**Comment by AndrewWangCH** [comment]
I solove this problem.
And thank you for your guidance.
