### ISSUE TITLE
'RoIAlignRotated' object has no attribute 'out_size'

### ISSUE THREAD

**Issue by gys1287009045** [open-mmlab/mmrotate#40]
Modify the 101 line of rotate_single_level_roi_extractor.py:
          out_size = self.roi_layers[0].out_size
to:
          out_size = self.roi_layers[0].output_size[0]

**Comment by yangxue0827** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/roi_extractors/single_level_roi_extractor.py#L60
![image](https://user-images.githubusercontent.com/29257168/155886569-60b36cdb-cb3b-425f-90b9-55a083afa3ee.png)
@zytx121

**Comment by DangChuong-DC** [comment]
I found potential error if change the line of code as suggestion due to mismatches between ops in `mmcv`
+ `RoIAlignRotated`:
https://github.com/open-mmlab/mmcv/blob/fd3a1a16ea1d0b3def8719816007a5d6fd6b432e/mmcv/ops/roi_align_rotated.py#L161

+ Meanwhile, for `RiRoIAlignRotated`:
https://github.com/open-mmlab/mmcv/blob/fd3a1a16ea1d0b3def8719816007a5d6fd6b432e/mmcv/ops/riroi_align_rotated.py#L121

Here is my temporary fix:
![temp_fixes1](https://user-images.githubusercontent.com/40515271/156176534-87fe60d0-be0e-4aa7-acd6-d0e8e4fbd2f7.png)

**Comment by yangxue0827** [comment]
Could you submit a PR to help us fix this bug? @DangChuong-DC

**Comment by DangChuong-DC** [comment]
PR is ready #51

**Comment by LUO77123** [comment]
修改了出现这类问题：TypeError: can't multiply sequence by non-int of type 'tuple'

**Comment by zytx121** [comment]
Hi @gys1287009045 
It is a bug that has been merged to the dev branch but still not merged to main branch https://github.com/open-mmlab/mmrotate/pull/51
You could pull code from the dev branch and try again.
