### ISSUE TITLE
one object has two predicted classes in oriented-reppoints

### ISSUE THREAD

**Issue by xypu98** [open-mmlab/mmrotate#426]
I use oriented-reppoints for a ship detection task.
But I discover some objects get two classes prediction result.
It seems no to be a very difficult classification task for model to define which class the ship is.
Is it possible that there are any problems on the oriented-reppoints network code or some parameters I should pay attention to?
Thanks a lot!
![image](https://user-images.githubusercontent.com/36292201/181056900-e51f6e65-b56d-4f2a-a237-7e41bbec2aca.png)

**Comment by yangxue0827** [comment]
I think ship classification is a fine-grained classification problem, which is a more difficult task for detection models. 
Besides, compared with optical images, SAR images contain less information, which is not friendly to fine-grained classification.

**Comment by yangxue0827** [comment]
As for one object being predicted to be multiple predictions, this is because we use intra-class nms.

**Comment by xypu98** [comment]
> As for one object being predicted to be multiple predictions, this is because we use intra-class nms.

Thanks for your analysis. It is helpful to improve my model's performance.

**Comment by jistiak** [comment]
@yangxue0827 > As for one object being predicted to be multiple predictions, this is because we use intra-class nms.

Is it possible to implement the inter-class nms too by changing any parameter somewhere? If I want just one prediction per bbox, what is the best way to move ahead after running the inference function? Even as a post-processing step. Thanks :)
