### ISSUE TITLE
train rotated-fcos  ,config is rotated_fcos_r50_fpn_1x_dota_le90.py ，but i cannot get the same mAP.

### ISSUE THREAD

**Issue by mutouoa** [open-mmlab/mmrotate#430]
train rotated-fcos  ,config is rotated_fcos_r50_fpn_1x_dota_le90.py ，but i cannot get the same mAP.
my mAP :

<img width="650" alt="image" src="https://user-images.githubusercontent.com/20034831/181437908-25d352f9-c24b-4d77-96f8-056ec82bc53e.png">

**Comment by mutouoa** [comment]
@lindahua @grimoire @canoe-Z

**Comment by mutouoa** [comment]
close

**Comment by liuyanyi** [comment]
It may be that the instability of Rotated IoU Loss affects the results. Is there any abnormality in Loss during training?
In my own experiments, the results of the Rotated IoU config will fluctuate, but not so low. 
Here is a strange Loss wave, but result goes fine.
![2d963b0d6b3f887fdb4f94c06b1bad0](https://user-images.githubusercontent.com/11705038/181445740-0fc5f5d4-24e3-4799-aa1f-760143b18396.png)

The CSL config is more stable, you can try that config too.

**Comment by yuyi1005** [comment]
@liuyanyi Hi, I tried FCOS+CSL.

The codes cannot run due to a 'seprate_angle' typo. I fixed that by changing 'seprate' to 'seperate', and then it can run, but the model trained by myself shows much lower mAP (about 3% lower). 

Is the pretrained model provided on the web trained on the 0.3.2 release? I suppose not, otherwise the 'seprate' typo should already been found. 

Could you help us find out the problem? Thanks a lot~
