### ISSUE TITLE
Is it possible to represent theta in [-pi, pi]?

### ISSUE THREAD

**Issue by mytkymt** [open-mmlab/mmrotate#537]
Hello folks,

I am searching for a way to represent the theta range in 2 * pi.
Though I know the theta range in 'le90' and 'le135' are pi, and 'oc' is pi/2, I want to implement the theta representation in [-pi, pi] to strictily differentiate heading angles of obb.

Does anyone know how to DIY it?

I appreciate any help you can provide.

**Comment by zytx121** [comment]
The official does not support `[-pi, pi]` detection now, because it needs to be trained with annotations with head direction information.

We will support DIY yourself ``RotatedBoxes`` class in mmrotate-1.x. Please refer to https://github.com/open-mmlab/mmrotate/blob/39da1b7e2ec5333fde64a0ec99bccce3a4e5b6b0/mmrotate/core/bbox/structures/rotated_boxes.py#L18

**Comment by mytkymt** [comment]
Thanks for your information!
I will try to DIY from my side. 
I will close here for now.

**Comment by Petros626** [comment]
@mytkymt did you trained your own range `[-pi, pi]`?

**Comment by yangxue0827** [comment]
range `[-pi, pi]`: https://github.com/open-mmlab/mmrotate/pull/1061

**Comment by Petros626** [comment]
Thank you for the quick answer, so supported is:
`Oc`
`Le90`
`Le135`
`Full360`

Which performed the best for the most tasks? What would you recommend for KITTI? 

@yangxue0827 any recommendations?

**Comment by Petros626** [comment]
@yangxue0827 any recommendations?
