### ISSUE TITLE
Does any of the models support running an inference on an env with CPU?

### ISSUE THREAD

**Issue by sulebaynes** [open-mmlab/mmrotate#556]
First of all thanks a lot for your support for the open source community! 

I would like to pick and train a model with a customized dataset. Locally I have a GPU to train but once the model is trained, the inferences have to run on an environment with CPU. Is there a model which I can train but run on CPU?

Thanks in advance

**Comment by ssq01** [comment]
Most of the models don't support inference on CPU because rotated nms operator is based on CUDA, which can only be used on GPU. However, here is Rotated Retinanet, Oriented RCNN, ROI Transformer which can be exported by mmdeploy, then you can run your inferences on ONNX Runtime backend. You can refer to https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/04-supported-codebases/mmrotate.md for more information.
