### ISSUE TITLE
How the model deal with the negative coordinates?

### ISSUE THREAD

**Issue by vincentdeeplearn** [open-mmlab/mmrotate#89]
Hi, it's great job for  mmrotate.

I use the script to crop DOTA1_0 to tiles:
   - python tools/data/dota/split/img_split.py --base_json tools/data/dota/split/split_configs/dota1_0/ss_trainval.json

But these are some negative coordinates for gt-box in tiles. e.g:
 - 22.0 131.0 -2.0 135.0 -10.0 64.0 12.0 61.0 small-vehicle 2

I train with such files is OK. My question is: whether the model ignore the wrong  input label or  the negative coordinates is acceptable for our model inputs? How the model deal with for the negative coordinates?

**Comment by yangxue0827** [comment]
Negative coordinates are not equal to wrong coordinates. In fact, there is no requirement that the coordinate value must be positive.
The data clipping operation inevitably produces negative coordinates, but this does not affect normal training. In fact, the negative coordinates on the sub-image are not necessarily negative when mapped back to the large image.

**Comment by vincentdeeplearn** [comment]
OK. Thanks. 
The speed of reply is amazing.

**Comment by vincentdeeplearn** [comment]
OK. Thanks. 
The speed of reply is amazing.

**Comment by xiaoshun1007** [comment]
你好，由于我的检测目标都比较大，分割完图片后，右侧子图x坐标都是负数，模型训练时loss都是nan，所以，是否为负坐标导致
Hello, because my detection targets are relatively large, after the image is segmented, the X coordinates of the right subgraph are negative, and the loss during model training is Nan, So, is it caused by negative coordinates：

![image](https://user-images.githubusercontent.com/74587741/168788091-0921c650-158d-4211-93ef-3cec76d2eab7.png)

` mmrotate - INFO - Epoch [6][600/1300] lr: 2.500e-03, eta: 3:14:54, time: 0.286, data_time: 0.008, memory: 3678, s0.loss_cls: nan, s0.loss_bbox: nan, sr0.loss_cls: nan, sr0.loss_bbox: nan, loss: nan, grad_norm: nan`
